version: '3.3'
services:
  config:
    image: mdemo/config-service:v1.0
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 200M
    ports:
      - 8888:8888
    networks:
          - webnet
networks:
  webnet:
